version: "3"

services:
  efb:
    build: .
    restart: always
    
#   ports:
#     - "127.0.0.1:8000:8000"
    volumes: 
      - "./config:/usr/src/app/ehforwarderbot/profiles"
    depends_on:
      - go-cqhttp

  go-cqhttp:
    build: ./go-cqhttp
    restart: always
#   ports: 
#     - "127.0.0.1:5700:5700"
    volumes:
      - "./cqhttp_data:/data"
